version: '2'
services:
  electron:
    build: electron
    ports:
      - "5900"
    network_mode: host
    privileged: true
    restart: always
  vnc:
    build: vnc
    ports:
      - "80"
    network_mode: host
    privileged: true
    restart: always
  networking:
    build: networking
    network_mode: host
    privileged: true
    restart: no
    labels:
      io.balena.features.dbus: '1'

