version: '2'
services:
  dashboard:
    build: dashboard
    ports:
      - "5900"
    network_mode: host
    privileged: true
    restart: always
  remote:
    build: remote
    ports:
      - "80"
    network_mode: host
    privileged: true
    restart: always
